# General
name: Minimal-Block
description: "Minimalistic, friendly, responsive."
url: https://drvy.github.io/minimal-block

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: drvy
twitter: drvymonkey
github: drvy
google: +DrvyMonkey

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
